version: '2'
services:
    brewery-app:
        image: brewery
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_COUCHBASE_BOOTSTRAP_HOSTS=brewery-couchbase
            - SPRING_COUCHBASE_BUCKET_NAME=brewery
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=internal
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=internal
            - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
    brewery-couchbase:
        extends:
            file: couchbase.yml
            service: brewery-couchbase
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
